#!/usr/bin/env bash
# Installing nginx on our webserver
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' > /var/www/html/index.html
