#!/usr/bin/env bash
#display hours from 0 to 12
#display i from 1 to 59
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour";
    minute=1;
    while [ $minute -lt 60 ]
    do
        echo "$minute";
        minute=$((minute + 1));
    done
    hour=$((hour + 1))
done
